steps:
  - label: ":pipeline::fleet::seedling: Trigger Observability Kibana Tests for ${ENVIRONMENT}"
    command: echo "replace me with Observability specific Kibana tests"
    agent:
      image: "docker.elastic.co/ci-agent-images/basic-buildkite-agent:1688566364"

  - label: ":pipeline::lock::seedling: Trigger Security Kibana Tests for ${ENVIRONMENT}"
    command: echo "replace me with Security specific Kibana tests"
    agent:
      image: "docker.elastic.co/ci-agent-images/basic-buildkite-agent:1688566364"
  - label: ":pipeline::kibana::seedling: Trigger Kibana Serverless Tests for ${ENVIRONMENT}"
    trigger: kibana-serverless
    build:
      env:
        ENVIRONMENT: ${ENVIRONMENT}
      message: Triggered by pipeline.tests.qa.yaml
      branch: $BUILDKITE_BRANCH
      commit: $BUILDKITE_COMMIT
  - wait: ~

  - label: ":cookie: Bake period of 24 hours"
    command: "sleep 86400"
